### ISSUE TITLE
There is an error while unwrapping files 

### ISSUE THREAD

**Issue by EnderRobber101** [Deonte/crossy-road-clone#1]
private static let largeTree = SCNScene(named: "art.scnassets/LargeTree.scn")!

        private static let mediumTree = SCNScene(named: "art.scnassets/MediumTree.scn")!
        
        private static let smallTree = SCNScene(named: "art.scnassets/SmallTree.scn")!
        
        private static let tallestTree = SCNScene(named: "art.scnassets/TallestTree.scn")!
        
        private static let rock = SCNScene(named: "art.scnassets/Rock.scn")!
        
        private static let blueCar = SCNScene(named: "art.scnassets/BlueCar.scn")!
        
        private static let greenCar = SCNScene(named: "art.scnassets/GreenCar.scn")!
        
        private static let purpleCar = SCNScene(named: "art.scnassets/PurpleCar.scn")!
        
        private static let taxiCar = SCNScene(named: "art.scnassets/TaxiCar.scn")!
        
        private static let sportsCar = SCNScene(named: "art.scnassets/SportsCar.scn")!
        
        private static let blueTruck = SCNScene(named: "art.scnassets/BlueTruck.scn")!
        
        private static let redTruck = SCNScene(named: "art.scnassets/RedTruck.scn")!
        
        
        There a error on these lines for me That says "Fatal error: Unexpectedly found nil while unwrapping an Optional value" Could you help?

**Comment by Deonte** [comment]
More than likely the LargeTree asset isn’t loading correctly, or it might because the file is missing for some odd reason. If that’s the only error, a quick workaround to check the app out would be to change the line to **private static let largeTree = SCNScene(named: "art.scnassets/MediumTree.scn")!**

**Comment by EnderRobber101** [comment]
That fixed it thank you so much! :) 👍
